### ISSUE TITLE
poetry or conda or smtn for library management? >.<

### ISSUE THREAD

**Issue by Jeremy5909** [alorans/DesmosAudio#1]
**Is your feature request related to a problem? Please describe.**
grr... manual library installation... am I right? 

**Describe the solution you'd like**
we use poetry or conda or smtn so it auto installs these idk if this is good idea tho

**Describe alternatives you've considered**
I've also considered not being lazy but \shrug

**Additional context**
meow meow meow mewo

**Comment by alorans** [comment]
Added requirements.txt for automatic library installation.

**Comment by alorans** [comment]
Added requirements.txt for automatic library installation.
